
import sys
sys.path.append('..')

import os
import argparse
import numpy as np
from dataset import *
from objects import *
from dgl.data.utils import save_graphs
from dgl.data.utils import load_graphs
from evaluation import *
from agent import *
from train_preprocess import *
import hyperparameters as hp
import copy
import joblib

def train_batch(gs, ls, agent):
    loss = agent.update_by_extrusion(ls, gs)
    return loss

def read_ids(ids_file):
    if not os.path.isfile(ids_file):
        raise FileNotFoundError(
            "Could not find '" + ids_file + "'. The id lists are written by "
            "train_preprocess.py into the directory it was run from. Either run train.py "
            "from that same directory, or pass --train_ids / --validate_ids.")
    return read_file_to_list(ids_file)

def load_train_step(data_path, seq_id, step_index):
    """
    Load the (positive, negative) pair generated by train_preprocess.py for one step.
    Returns None once the sequence has no more steps on disk.
    """
    step_folder = os.path.join(data_path, seq_id, 'train')
    paths = [os.path.join(step_folder, str(step_index) + '_' + str(label) + '_' + kind + '.joblib')
             for label in (1, 0) for kind in ('g', 'e')]

    if not all(os.path.isfile(p) for p in paths):
        return None

    try:
        return [joblib.load(p) for p in paths]
    except Exception as e:
        print('failed to load step', step_index, 'of', seq_id, ':', repr(e))
        return None

def load_sequence(data_mgr, data_path, seq_id):
    gt_folder = os.path.join(data_path, seq_id, 'gt')
    if not os.path.isdir(gt_folder):
        return None
    try:
        return data_mgr.load_processed_sequence(gt_folder)
    except Exception as e:
        print('failed to load sequence', seq_id, ':', repr(e))
        return None

def train(data_path, folder, train_ids_file='train_ids.txt', validate_ids_file='validate_ids.txt'):

    train_ids = read_ids(train_ids_file)
    validate_ids = read_ids(validate_ids_file)

    if os.path.exists(folder) is True:
        print('removing previous training output in', folder)
        shutil.rmtree(folder)
    if not os.path.exists(folder):
        os.makedirs(folder)

    agent = Agent(folder)
    data_mgr = DataManager()

    train_loss_list = []
    validation_loss_list = []
    min_validation_loss = np.inf

    gs = []
    ls = []

    for epoch_index in range(hp.train_epoch_num):
        print('epoch', epoch_index , '--------------------------------------------')
        agent.train_mode()
        used_seq_count = 0
        step_count = 0

        for seq_index, seq_id in enumerate(train_ids):
            print('seq index', seq_index, 'seq id', seq_id)

            gt_seq = load_sequence(data_mgr, data_path, seq_id)
            if not gt_seq:
                continue

            used_seq_count += 1

            for step_index, gt_step in enumerate(gt_seq):
                step = load_train_step(data_path, seq_id, step_index)
                if step is None:
                    break
                pos_g, pos_e, neg_g, neg_e = step

                if pos_g and pos_e and neg_g and neg_e:
                    step_count += 1

                    pos_g.encode_with_extrusion(pos_e)
                    gs.append(pos_g)
                    ls.append(to_tensor([1]))

                    neg_g.encode_with_extrusion(neg_e)
                    gs.append(neg_g)
                    ls.append(to_tensor([0]))

                    if len(gs) >= hp.batch_size:
                        loss = train_batch(gs, ls, agent)
                        gs = []
                        ls = []
                        train_loss_list.append(loss)
                        write_list_to_file(os.path.join(folder, 'trainloss.txt'), train_loss_list)
                        agent.save_weights()

        print('epoch', epoch_index, 'used', used_seq_count, 'of', len(train_ids),
              'sequences,', step_count, 'training steps,', len(train_loss_list), 'batches so far')

        if step_count == 0:
            raise RuntimeError(
                "No training data was found under '" + data_path + "'. Expected "
                "<data_path>/<seq_id>/gt/*.joblib and <data_path>/<seq_id>/train/*.joblib "
                "produced by train_preprocess.py, for the ids listed in " + train_ids_file + ".")

        # validate after each training epoch
        agent.save_weights()
        validation_loss = validate(data_path, folder, validate_ids, agent)
        validation_loss_list.append(validation_loss)
        write_list_to_file(os.path.join(folder, 'validationloss.txt'), validation_loss_list)
        if validation_loss <= min_validation_loss:
            min_validation_loss = validation_loss
            agent.save_best_weights()

def validate(data_path, folder, validate_ids=None, agent=None):

    print('validation----------------------------------------')

    if validate_ids is None:
        validate_ids = read_ids('validate_ids.txt')

    if agent is None:
        agent = Agent(folder)
        agent.load_weights()

    agent.eval_mode()

    data_mgr = DataManager()

    total_rank_sum = 0

    for validation_index, seq_id in enumerate(validate_ids):
        print('validation_index', validation_index, 'seq_id', seq_id)

        gt_seq = load_sequence(data_mgr, data_path, seq_id)
        if not gt_seq:
            continue

        for step_index, gt_step in enumerate(gt_seq):
            step = load_train_step(data_path, seq_id, step_index)
            if step is None:
                break
            pos_g, pos_e, neg_g, neg_e = step

            if pos_g and pos_e and neg_g and neg_e:
                gt_zone_graph = gt_step[0]
                gt_extrusion = gt_step[1]
                # the last step of a sequence has no extrusion to rank
                if gt_zone_graph is None or gt_extrusion is None:
                    continue
                extrusions = get_proposals(gt_zone_graph)
                agent_ranked_extrusions = sort_extrusions_by_agent(extrusions, gt_zone_graph, agent)
                for i, extrusion in enumerate(agent_ranked_extrusions):
                    if gt_extrusion.hash() == extrusion.hash():
                        total_rank_sum += i
                        break

    print('validation rank sum', total_rank_sum)
    agent.train_mode()

    return total_rank_sum

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='ZoneGraph')
    parser.add_argument('--data_path', default='processed_data', type=str)
    parser.add_argument('--output_path', default='train_output', type=str)
    parser.add_argument('--train_ids', default='train_ids.txt', type=str)
    parser.add_argument('--validate_ids', default='validate_ids.txt', type=str)
    args = parser.parse_args()

    train(args.data_path, args.output_path, args.train_ids, args.validate_ids)
